FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    curl \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .
ENV PYTHONPATH=/app:/app/src:$PYTHONPATH
# Run app
CMD ["uvicorn", "src.app.api:app", "--host", "0.0.0.0", "--port", "8000"]
